### ISSUE TITLE
Zelenaci

### ISSUE THREAD

**Issue by jakubvasi** [MarrekNozka/chytrosti#1]
:cry: :cry:
![Pekari](https://user-images.githubusercontent.com/31956745/140305026-8ebf0f9f-d141-4088-85e9-41a7ef2f4887.PNG)

:sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob:
![Zelenaci](https://user-images.githubusercontent.com/31956745/140305043-6456919d-aab9-48fa-8e73-161f374fbd54.png)

**Comment by Wunson** [comment]
![image](https://user-images.githubusercontent.com/31744188/140306642-fa83d33e-34fb-4f9e-8ea8-2bc1d9604725.png)
credit: Kryštof

**Comment by jakubvasi** [comment]
![Nozkeus](https://user-images.githubusercontent.com/31956745/140376219-79e771ad-9617-4a66-9a0e-f769fbdce670.jpg)

**Comment by romansvozil** [comment]
Také mám tento problem, specifikace systemu:

Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

Dekuji za rychlou opravu. :+1:

**Comment by Kryshi** [comment]
![image](https://user-images.githubusercontent.com/32136000/140545804-12f28d53-c9ce-4d0d-b3a1-74386754c1a8.png)
Certified 1984 moment
![image](https://user-images.githubusercontent.com/32136000/140546676-5238c2c7-65a1-41f8-bf86-6503b54fce94.png)

**Comment by vyky123** [comment]
Mám podobný problém a mohu potvrdit, že se vyskytuje jak na Debianu, tak na Androidu a dokonce i na operačním systému, jehož jméno nesmíme vyslovit.

**Comment by MarrekNozka** [comment]
Pánové mrzí mě, pokud jsem smazal něco, co jsem neměl... mám ale za to, že jsem před lety upozorňoval, že k tomu jistě dojde. Bezdůvodné to jistě nebylo, prostě přišla další třída.
