### ISSUE TITLE
Nefunguje odkaz na stránce https://chytrosti.marrek.cz/mit.html

### ISSUE THREAD

**Issue by peoblouk** [MarrekNozka/chytrosti#2]
![image](https://user-images.githubusercontent.com/60695220/211086908-941ef8b3-e41b-4652-9079-ccc0495593f5.png)

http://www.tajned.cz/2016/10/i2c-relativne-jednoduse/

**Comment by MarrekNozka** [comment]
Opraveno. Děkuji.
